### ISSUE TITLE
Unstable Internet connections via Wi-Fi

### ISSUE THREAD

**Issue by aiden-leong** [mikeeq/xiaomi_ax3200_openwrt#11]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/7299189/159175870-0b95238c-d923-4b6e-8170-12dad791b988.png">

Same issues are reported by other users.

Update: SSH connection is stable.

**Comment by mikeeq** [comment]
I have two different AX3200 devices and use them on daily basis. I don't have any issues with WiFi 2.4GHz or 5GHz.

**Comment by mikeeq** [comment]
You can always put some logs here and we can try to debug it together ;)
