### ISSUE TITLE
Setting up new interface dhcp works randomly

### ISSUE THREAD

**Issue by Beermaster90** [mikeeq/xiaomi_ax3200_openwrt#13]
Setting up new interface(example for iot devices) and setting dhcp works randomly at lucy interface.

1. Assign Wlan -> New interface
2. Set up new static interface
3. Use IP subnet example 192.168.2.1/24
4. Enable DHCP

Clients gets randomly ip at dhcp from original LAN interface. IP being 192.168.1.xxx.
Deleting interface completely and recreating sometimes helps and users starts getting correct ips like 192.168.2.xxx

**Comment by vedranius** [comment]
Is this still an issue?

**Comment by Beermaster90** [comment]
> 

No idea. I changed to official build and no issues anymore.
