### ISSUE TITLE
CH341A programmer 

### ISSUE THREAD

**Issue by littlej956** [mikeeq/xiaomi_ax3200_openwrt#17]
Hi, can you somehow confirm if it is possible to enable telnet on a RB01 model with factory telnet disabled using the method described here: 

 [CH341A programmer] (https://forum.openwrt.org/t/adding-openwrt-support-for-xiaomi-redmi-router-ax6s-xiaomi-router-ax3200/111085/151?u=mikeeq)  

Thanks

**Comment by mikeeq** [comment]
There's an UART flash section in the readme now, use that instead ;)
