### ISSUE TITLE
Small omission in upgrade instructions

### ISSUE THREAD

**Issue by L4rryFisherman** [mikeeq/xiaomi_ax3200_openwrt#20]
First line says:

`# SSH to OpenWRT flashed router
ssh 192.168.1.1`

If you upgrade right after installing this logs you in to 'user' which isn't set, so a blank or other password doesn't work.

Fixed by:
`# SSH to OpenWRT flashed router
ssh root@192.168.1.1`

**Comment by mikeeq** [comment]
Updated in https://github.com/mikeeq/xiaomi_ax3200_openwrt/pull/21
