### ISSUE TITLE
What firmware for telnet enabled EU AX3200

### ISSUE THREAD

**Issue by vale-max** [mikeeq/xiaomi_ax3200_openwrt#27]
Hello @mikeeq 
I found an AX3200 that had been shelved a couple years ago, it has FW 1.0.35 and telnet enabled.
Should I update the fw to latest before flashing the openwrt image or it does not matter?

**Comment by mikeeq** [comment]
`a couple years ago`? Router was released 02 July 2021, so you can have for max ~1.5y :D Make sure you have the same device as it is described in the readme :D Yeah, if it has telnet you can safely install openwrt on it ;)

**Comment by vale-max** [comment]
manufactured 8/2021, box opened yesterday. The shelf was not mine, from a shop that had closed probably shortly after receiving it. Let's update it then.
