### ISSUE TITLE
it seems that this method doesn't work on AX6s(RB03).

### ISSUE THREAD

**Issue by CCA2878** [mikeeq/xiaomi_ax3200_openwrt#3]
After I complete "mtd -r write", the router restarts and still works on official firmware, not openwrt.
On the post https://forum.openwrt.org/t/adding-openwrt-support-for-xiaomi-redmi-router-ax6s-xiaomi-router-ax3200, I hear that it may need "mtd write rootfs overlay",but I can't find it.Even the firmware files compiled by myself don't contain "rootfs".
How to deal with the problem?

**Comment by GTian5418** [comment]
> After I complete "mtd -r write", the router restarts and still works on official firmware, not openwrt. On the post https://forum.openwrt.org/t/adding-openwrt-support-for-xiaomi-redmi-router-ax6s-xiaomi-router-ax3200, I hear that it may need "mtd write rootfs overlay",but I can't find it.Even the firmware files compiled by myself don't contain "rootfs". How to deal with the problem?


you should try this
cd /tmp
nvram set flag_boot_rootfs=0
nvram set "boot_fw1=run boot_rd_img;bootm"
nvram set flag_boot_success=1
nvram set flag_try_sys1_failed=0
nvram set flag_try_sys2_failed=0
nvram commit
mtd -r write sysupgrade.bin firmware
