### ISSUE TITLE
The ROM size is 30mb only

### ISSUE THREAD

**Issue by phantastar** [mikeeq/xiaomi_ax3200_openwrt#4]
That firmware has given me a good experience in usage. However I found the disk space is 31.58mb only while temp space occupied 113.71mb (given that this device has 128mb of ROM size). I'm curious what happened?
![image](https://user-images.githubusercontent.com/25948362/156877060-c70ed6d0-70ea-4fbe-b0ad-5a44e54739e6.png)

**Comment by mikeeq** [comment]
That should be resolved with the new release. Remember to first flash it using `mtd -r write factory.bin firmware`

**Comment by phantastar** [comment]
> That should be resolved with the new release. Remember to first flash it using `mtd -r write factory.bin firmware`

Thank you Mike! It's done and working properly!!!
