### ISSUE TITLE
I tried to install mwan3 but it didn't work

### ISSUE THREAD

**Issue by bear1999** [mikeeq/xiaomi_ax3200_openwrt#7]
![untitled](https://user-images.githubusercontent.com/9910003/158230329-1d5e74e0-3e14-47aa-b692-483549153aa3.PNG)
Hi sir, i tried install mwan3 but i still have issue about kernel.

Sorry this is my first time using openwrt, thanks.

**Comment by mikeeq** [comment]
Please use official release instead, then you will have access to official pkgs and you will be able to install them as kernel checksum will match. Thanks!
